//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 07:32:24 PM CET 
//


package jaxbGenerated.datenxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}rsmodell"/&gt;
 *         &lt;element ref="{}datum"/&gt;
 *         &lt;element ref="{}uhrzeit"/&gt;
 *         &lt;element ref="{}geldkreise"/&gt;
 *         &lt;element ref="{}metatalente"/&gt;
 *         &lt;element ref="{}zauberquellen"/&gt;
 *         &lt;element ref="{}namenaufseiten"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rsmodell",
    "datum",
    "uhrzeit",
    "geldkreise",
    "metatalente",
    "zauberquellen",
    "namenaufseiten"
})
@XmlRootElement(name = "config")
public class Config {

    @XmlElement(required = true)
    protected String rsmodell;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String datum;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String uhrzeit;
    protected boolean geldkreise;
    protected boolean metatalente;
    protected boolean zauberquellen;
    protected boolean namenaufseiten;

    /**
     * Gets the value of the rsmodell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsmodell() {
        return rsmodell;
    }

    /**
     * Sets the value of the rsmodell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsmodell(String value) {
        this.rsmodell = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the uhrzeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUhrzeit() {
        return uhrzeit;
    }

    /**
     * Sets the value of the uhrzeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUhrzeit(String value) {
        this.uhrzeit = value;
    }

    /**
     * Gets the value of the geldkreise property.
     * 
     */
    public boolean isGeldkreise() {
        return geldkreise;
    }

    /**
     * Sets the value of the geldkreise property.
     * 
     */
    public void setGeldkreise(boolean value) {
        this.geldkreise = value;
    }

    /**
     * Gets the value of the metatalente property.
     * 
     */
    public boolean isMetatalente() {
        return metatalente;
    }

    /**
     * Sets the value of the metatalente property.
     * 
     */
    public void setMetatalente(boolean value) {
        this.metatalente = value;
    }

    /**
     * Gets the value of the zauberquellen property.
     * 
     */
    public boolean isZauberquellen() {
        return zauberquellen;
    }

    /**
     * Sets the value of the zauberquellen property.
     * 
     */
    public void setZauberquellen(boolean value) {
        this.zauberquellen = value;
    }

    /**
     * Gets the value of the namenaufseiten property.
     * 
     */
    public boolean isNamenaufseiten() {
        return namenaufseiten;
    }

    /**
     * Sets the value of the namenaufseiten property.
     * 
     */
    public void setNamenaufseiten(boolean value) {
        this.namenaufseiten = value;
    }

}
