//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 07:32:24 PM CET 
//


package jaxbGenerated.datenxml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eigenschaftswertezukaufbar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eigenschaftswertezukaufbar"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}eigenschaftswerte"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}kaufbar"/&gt;
 *         &lt;element ref="{}gekauft"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eigenschaftswertezukaufbar", propOrder = {
    "kaufbar",
    "gekauft"
})
@XmlSeeAlso({
    Eigenschaftswerteastrale.class,
    Eigenschaftswertezukaufbar503325 .class
})
public class Eigenschaftswertezukaufbar
    extends Eigenschaftswerte
{

    @XmlElement(required = true)
    protected BigInteger kaufbar;
    @XmlElement(required = true)
    protected BigInteger gekauft;

    /**
     * Gets the value of the kaufbar property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKaufbar() {
        return kaufbar;
    }

    /**
     * Sets the value of the kaufbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKaufbar(BigInteger value) {
        this.kaufbar = value;
    }

    /**
     * Gets the value of the gekauft property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGekauft() {
        return gekauft;
    }

    /**
     * Sets the value of the gekauft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGekauft(BigInteger value) {
        this.gekauft = value;
    }

}
